name: CMake-Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
    - uses: actions/checkout@v2

    - name: Update Git Submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: linux-${{env.BUILD_TYPE}}

    - name: Configure CMake
      run: cmake gametemplate -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_EDITOR=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

    - uses: actions/upload-artifact@v2
      with:
        name: ${{env.BUILD_TYPE}}
        path: |
          build/**/*.exe
          build/**/EditorResources
          build/**/EngineResources
          build/**/GameResources
          !build/**/CMakeFiles