name: CMake-MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 50

    steps:
    - uses: actions/checkout@v2

    - name: Update Git Submodules
      run: git submodule update --init --recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: osx-${{env.BUILD_TYPE}}

    - name: Configure CMake
      run: cmake gametemplate -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DJLE_BUILD_EDITOR=ON -DJLE_BUILD_UNITY=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 6

    - uses: actions/upload-artifact@v4
      with:
        name: ${{env.BUILD_TYPE}}
        path: |
          build/**/*.exe
          build/**/EditorResources
          build/**/EngineResources
          build/**/GameResources
          !build/**/CMakeFiles